---
- name: InstaLL nginx web server
  hosts: all
  become: yes
  tasks:
    - name: check file exists
      command: ls /tmp/file
      register: file_check
      ignore_errors: yes

    - name: Print file exist
      debug: 
        msg: "file exist"
      when: file_check.rc == 0

    - name: Print file not exist
      debug:
        msg: "file not exist"
